name: Android CI

on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        run: |
          haxelib install hxcpp
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install actuate
          haxelib install extension-webm
          haxelib install linc_luajit
          haxelib install hxCodec
          haxelib install hxvlc
          haxelib install hxjsonast
          haxelib install format
          haxelib install polymod
          haxelib install thx.core
          haxelib install tink_core
          haxelib install msignal
          haxelib install newgrounds
          haxelib install openfl
          haxelib install lime
          haxelib install flixel-tools

      - name: Setup Android
        run: |
          haxelib run lime setup android

      - name: Create Version Tag
        run: echo "${{ github.run_id }}" > VERSION

      - name: Compile
        run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id }}" -D officialBuild

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/
